### ISSUE TITLE
No debug log on error

### ISSUE THREAD

**Issue by KatzeMitHut** [event-catalog/generator-asyncapi#11]
I tried to generate files from a valid AsyncAPI document regarding to AsyncAPI Studio and got this error. It worked with a different document, but with this one I got:

> Processing 1 AsyncAPI files...
> Processing /home/my-catalog/asyncapi-files/asyncapi.yaml
> Failed to parse AsyncAPI file
> Run with debug option in the generator to see diagnostics

To get the debug logs I tried

> DEBUG=* npm run generate

and 

> npm run generate --debug

But I always got the same output shown above.

**Comment by boyney123** [comment]
Thanks for raising an issue, I will take a look

**Comment by boyney123** [comment]
Thanks @KatzeMitHut , should be fixed now.

You can find docs here https://www.eventcatalog.dev/docs/development/plugins/async-api/api#debug

It was originally a debug flag on the generator itself, but I like idea of the CLI flag too, so I added that :). 

Thanks for raising the issue.

**Comment by KatzeMitHut** [comment]
Thanks for addressing this so quickly :)
