### ISSUE TITLE
Generator exports yml when given a spec written in json

### ISSUE THREAD

**Issue by codingnuclei** [event-catalog/generator-asyncapi#36]
### I tried this:

Given 
``` generators: [
    [
      '@eventcatalog/generator-asyncapi',
      {
        domain: {
          id: 'userManagement',
          name: 'User Management',
          version: '1.0.0',
        },
        services: [
          {
            path: path.join(
              __dirname,
              '../../services/user-management/asyncapi-files',
              'user-service.json',
            ),
          },
        ],
      },
    ]
]
```

Where `user-service.json` is a valid asyncAPI JSON schema

### This happened:

The schema added to the service in the Catalog is YML in a `.json` file

### I expected this:

The generator should maintain the format given

### Is there a workaround?

no :(

### Anything else?

Looks like this line is the culprit:
https://github.com/event-catalog/generator-asyncapi/compare/eeb5d45..main#diff-a2a171449d862fe29692ce031981047d7ab755ae7f84c707aef80701b3ea0c80R258

### Community Notes

* Please vote by adding a 👍 reaction to the issue to help us prioritize.
* If you are interested to work on this issue, please leave a comment.

**Comment by boyney123** [comment]
Thanks @codingnuclei , is this an example of what you are using? https://github.com/asyncapi/spec-json-schemas/blob/master/schemas/3.0.0.json

**Comment by codingnuclei** [comment]
Apologies - I had just not clicked the button to post 😆 

[user-service.json](https://github.com/user-attachments/files/17018942/user-service.json)

**Comment by boyney123** [comment]
This should be fixed now, please reopen or raise an issue if you find any problems.

Thanks for raising the issue.
