### ISSUE TITLE
The Generator fails when running the "Processing service" step

### ISSUE THREAD

**Issue by frodesorhoy** [event-catalog/generator-asyncapi#41]
### I tried this:

I'm running the command "npm run generate". 

The data used is the "eventcatalog-asyncapi-example". Cloned the project

### This happened:

It fails with the message:

Processing service: Orders Service (v1.0.1)
Error loading plugin: Error: ENOENT: no such file or directory, open 'C:\Tools\eventcatalog-asyncapi-example\services\Orders Service\C:\Tools\eventcatalog-asyncapi-example\asyncapi-files\orders-service.yml'
    at async open (node:internal/fs/promises:638:25)
    at async Object.writeFile (node:internal/fs/promises:1215:14)
    at async addFileToResource (C:\Tools\eventcatalog-asyncapi-example\node_modules\@eventcatalog\sdk\dist\index.js:176:3)
    at async src_default (C:\Tools\eventcatalog-asyncapi-example\node_modules\@eventcatalog\generator-asyncapi\dist\index.js:310:5)
    at async generate (file:///C:/Tools/eventcatalog-asyncapi-example/.eventcatalog-core/scripts/generate.js:50:9) {
  errno: -4058,
  code: 'ENOENT',
  syscall: 'open',
  path: 'C:\\Tools\\eventcatalog-asyncapi-example\\services\\Orders Service\\C:\\Tools\\eventcatalog-asyncapi-example\\asyncapi-files\\orders-service.yml'
}

### I expected this:

No error

### Is there a workaround?

Not that I can see

### EventCatalog Version

@eventcatalog/core": {"version": "2.7.16"}

### Node.js Version

v22.5.1

### Platform(s)

Windows

### Community Notes

* Please vote by adding a 👍 reaction to the issue to help us prioritize.
* If you are interested to work on this issue, please leave a comment.

**Comment by siualpinto** [comment]
It also happens for me
![image](https://github.com/user-attachments/assets/a1c4c0bc-acda-4cfb-b370-d8aaff073323)

**Comment by jcfore21** [comment]
I'm also getting this error, cloning directly and then trying the steps to get it to generate.  I even took my own custom .yml files and it fails at the same step for my services.  Seems to be an issue with the the paths for services.

![image](https://github.com/user-attachments/assets/e0cf9f11-5c82-4e54-8545-3f2d4b319768)

**Comment by boyney123** [comment]
We had some issues with windows OS and some node issues. These should be fixed in @eventcatalog/generator-asyncapi@2.1.0, try that version and let me know if you still see issues. Thanks!

**Comment by frodesorhoy** [comment]
Thanx. That did the trick. Using v2.1.* I'm now able to run the generators and the example sites.
