### ISSUE TITLE
Better handling of service filename

### ISSUE THREAD

**Issue by hpatoio** [event-catalog/generator-asyncapi#42]
### Use Case

I run the command `npm run generate` with an AsyncAPI file whose `info.title`  was:

```
info:
  title: Foo Service. See http://foo.com
  version: 1.0.0
```

Since [generator uses](https://github.com/event-catalog/generator-asyncapi/blob/main/src/index.ts#L251) `title` as filename this was created in `services` folder 

```
├── Foo Service. See http:
│   └── foo.com
│       ├── index.md
│       └── inventory-service.yml
```

### Proposed Solution

We can have different solution:

1. We "sanitize" the value in `info.title` before use it as a filename.
2. We allow an extra property `x-eventcatalog-service-id` that allow to specify a machine-friendly name for the service. If this is not set we can still fallback to point 1.

Something like:

```
info:
  title: Foo Service. See http://foo.com
  version: 1.0.0
  x-eventcatalog-service: foo-service
```

### Community Notes

* Please vote by adding a 👍 reaction to the issue to help us prioritize.
* If you are interested to work on this issue, please leave a comment.

**Comment by boyney123** [comment]
Thanks for raising @hpatoio .

I released a new version of the generator @eventcatalog/generator-asyncapi@1.0.3, if the service id is specified in the generator this is used for your serviceId and now folder name.

```
{
        // Set your own id for your services
        services: [
          { path: path.join(__dirname, 'asyncapi-files', 'payment-service.yml'), id: 'paymentservice'}
          { path: path.join(__dirname, 'asyncapi-files', 'fraud-detection-service.yml'), id: 'customservice'}
        ],
        domain: { id: 'payment', name: 'Payment', version: '0.0.1' },
    },
    ```
    
    Here is an example, the `customservice` and `paymentservice` will be the id of the service and folder name. 
    
    Hopefully this helps?

**Comment by hpatoio** [comment]
Everything works. I dug a bit into the code and not it's more clear to me how things works. 

IMHO you should make `id` mandatory. The code, and the conf, would be much simpler/clear (no fallback). In this way you could also remove `folderName` and use `id`.

My 2 cents.

**Comment by boyney123** [comment]
> Everything works. I dug a bit into the code and not it's more clear to me how things works.
> 
> IMHO you should make `id` mandatory. The code, and the conf, would be much simpler/clear (no fallback). In this way you could also remove `folderName` and use `id`.
> 
> My 2 cents.

I actually quite like this tbh, keeping things simple. We have a breaking change incoming @glc-omid #40, wonder if it makes sense to add this. I think it does... will make a PR this week to attach to the next major version.

**Comment by glc-omid** [comment]
We can also une slugified file name if serviceid not present

**Comment by hpatoio** [comment]
> We can also une slugified file name if serviceid not present

I think that this just make things more complicated without any real value to the user.  It's also more work on documentation side.

I don't get what's the problem with a conf like 

```
services: [
  { path: path.join(__dirname, 'asyncapi-files', 'inventory-service.yml'), id: 'my-service'}
],
```

1. You know exactly what will be the `id` of your service
2. You can use any "format" you want. CamelCase, snake_case etc ...
3. If for any reason you need to change the filename don't have to worry about any possible side effect
