### ISSUE TITLE
Generator Breaks other existing physical contents  

### ISSUE THREAD

**Issue by XaaXaaX** [event-catalog/generator-asyncapi#47]
### I tried this:

While using generators the plugins use rmService when versions match and recreate the service again with updated markdown , etc.. but they remove all physical contents 

A generaor removes any spec generated by other generator for the same service.
This becomes a problem as for exp. when openapi removes asyncapi spec or vise versa , this leads to have a failing spec tag in service page but no spec presented behind 

Maybe it can be applied at SDK level ??? 

Note: The issue created here but it is global in all plugins ,   

### This happened:

Add openapi and asyncapi for the same service with same version and running the generate command will keep only the last executed one ( in order presented in generators array of EC config ) 

The markdown state is tracked AND IS UPDATED but the physical spec file is removed 

### EventCatalog Version

latest

### Node.js Version

node --version 20

### Platform(s)

MacOS, Linux, Windows

### Community Notes

* Please vote by adding a 👍 reaction to the issue to help us prioritize.
* If you are interested to work on this issue, please leave a comment.

**Comment by boyney123** [comment]
This is now merged, thanks @XaaXaaX makes sense to me!
