### ISSUE TITLE
Make id mantatory and remove folderName

### ISSUE THREAD

**Issue by boyney123** [event-catalog/generator-asyncapi#49]
### Use Case

https://github.com/event-catalog/generator-asyncapi/issues/42#issuecomment-2367580826

### Community Notes

* Please vote by adding a 👍 reaction to the issue to help us prioritize.
* If you are interested to work on this issue, please leave a comment.
* If this issue is labeled **needs-discussion**, it means the spec has not been finalized yet. Please reach out in the [EventCatalog Discord](https://discord.com/invite/3rjaZMmrAm).

**Comment by hpatoio** [comment]
Not sure when you plan to release the new version but I can try to work on this if time is not too strict. Or maybe I can just do some testing and provide feedback. 

Let's not forget about documenting how to migrate existing catalogs.

**Comment by boyney123** [comment]
Now released in 2.0.0. Thanks for the idea, I think its a great step forward.
