### ISSUE TITLE
No such file or directory when calling npm run generate

### ISSUE THREAD

**Issue by acezar** [event-catalog/generator-asyncapi#60]
### I tried this:

I have cloned the [eventcatalog-asyncapi-example](https://github.com/event-catalog/eventcatalog-asyncapi-example) , did a npm install and a npm run generate on the working example without changing any file. Processing the domain and message was successful, but when it comes to processing the service it throws an ENOENT Error. Same issue occurs also for the "eventcatalog-openapi-example". Node version is 20.17.0.

### This happened:

Processing domain: Orders (v0.0.1)
 - Domain (v0.0.1) created
Processing message: OrderCreated (v1.0.1)
 - Message (v1.0.1) created
 - Schema added to message (v1.0.1)
Processing message: OrderUpdated (v1.0.1)
 - Message (v1.0.1) created
 - Schema added to message (v1.0.1)
Processing message: OrderCancelled (v1.0.1)
 - Message (v1.0.1) created
 - Schema added to message (v1.0.1)
Processing message: OrderCompleted (v1.0.1)
 - Message (v1.0.1) created
 - Schema added to message (v1.0.1)
Processing message: PaymentProcessed (v1.0.1)
 - Message (v1.0.1) created
 - Schema added to message (v1.0.1)
Processing message: InventoryReserved (v1.0.1)
 - Message (v1.0.1) created
 - Schema added to message (v1.0.1)
Processing message: ShipmentDelivered (v1.0.1)
 - Message (v1.0.1) created
 - Schema added to message (v1.0.1)
Processing service: Orders Service (v1.0.1)
Error loading plugin: Error: ENOENT: no such file or directory, open 'D:\eventCatalog2\eventcatalog-asyncapi-example\services\Orders Service\D:\eventCatalog2\eventcatalog-asyncapi-example\asyncapi-files\orders-service.yml'
    at async open (node:internal/fs/promises:639:25)
    at async Object.writeFile (node:internal/fs/promises:1212:14)
    at async addFileToResource (D:\eventCatalog2\eventcatalog-asyncapi-example\node_modules\@eventcatalog\sdk\dist\index.js:176:3)
    at async src_default (D:\eventCatalog2\eventcatalog-asyncapi-example\node_modules\@eventcatalog\generator-asyncapi\dist\index.js:320:7)
    at async generate (file:///D:/eventCatalog2/eventcatalog-asyncapi-example/.eventcatalog-core/scripts/generate.js:50:9) {
  errno: -4058,
  code: 'ENOENT',
  syscall: 'open',
  path: 'D:\\eventCatalog2\\eventcatalog-asyncapi-example\\services\\Orders Service\\D:\\eventCatalog2\\eventcatalog-asyncapi-example\\asyncapi-files\\orders-service.yml'

### Node.js Version

20.17.0

### Community Notes

* Please vote by adding a 👍 reaction to the issue to help us prioritize.
* If you are interested to work on this issue, please leave a comment.

**Comment by smalls257** [comment]
I've been playing around locally trying to get around it. Looks like a path issue. Index.ts L245 and a couple other places pop based on a '/'.  This doesn't work for windows, replacing with "\\" works for me locally. Probably need something more robust for Linux+ Windows. I'm not savvy with front-end apps else I'd get a PR out there.

**Comment by boyney123** [comment]
Thanks for raising the issue. `@eventcatalog/generator-asyncapi@2.1.0` is now out. Let me know if you still have any issues.

**Comment by acezar** [comment]
Thanks for the quick fix, I've updated the package.json of the asyncapi-example repo with the newest version of the generator and it works!

**Comment by boyney123** [comment]
Great to hear! Any more issues let us know. Good luck!
