### ISSUE TITLE
Generating channels from the AsynsAPI contract

### ISSUE THREAD

**Issue by hartmanjan1970** [event-catalog/generator-asyncapi#99]
### Use Case

Would it be posible for the channels to be generated from a Asyncapi contract? 
The generation of channels seems a logica action because these channels and there protocol usted are already defined in the contracts, therefore generating the channels seems a straight forward feature to me.

### Proposed Solution

Generating the channels could be a optional feature. 
Adding the channel to the message, because we know the sevice whos sendingthe message. 

### Community Notes

* Please vote by adding a 👍 reaction to the issue to help us prioritize.
* If you are interested to work on this issue, please leave a comment.
* If this issue is labeled **needs-discussion**, it means the spec has not been finalized yet. Please reach out in the [EventCatalog Discord](https://discord.com/invite/3rjaZMmrAm).

**Comment by boyney123** [comment]
Thanks @hartmanjan1970 , makes sense to me! Going to make in an opt in thing I think, something to configure with the generator, opting in will create the channels and link your messages to them.
